### ISSUE TITLE
Test Set

### ISSUE THREAD

**Issue by tangsirfly** [BasitAlawode/UVOT400#4]
Every sequence of the downloaded test set only has gt in the first picture, but nothing else. How to get the precise and success rate without all gt in the test set?

**Comment by BasitAlawode** [comment]
An evaluation server is being developed for the test set. Once it is completed, the link will be included in this repository.

**Comment by tangsirfly** [comment]
Thank you！I wonder if you can tell me the approximate online time of the evaluation server.
