### ISSUE TITLE
gt

### ISSUE THREAD

**Issue by tangsirfly** [BasitAlawode/UVOT400#5]
Excuse me, when I use the test set to test the model and get a series of prediction frames, I don't have the gt of the test set, how can I calculate the accuracy and success rate?

**Comment by BasitAlawode** [comment]
Hi. Similar to most open-air datasets, we are working on creating an evaluation server on the test set. This will be live as soon as possible and an update will be posted. Thank you.

**Comment by tangsirfly** [comment]
Hello, may I ask if the test platform is completed, and look forward to your answer

**Comment by BasitAlawode** [comment]
Hi. It's almost ready. Please check again very early next month. Thank you.
